### ISSUE TITLE
Add a profile page

### ISSUE THREAD

**Issue by GuiWukai** [chimano/SOEN341_SA2#129]
As a user I would like to check my profile to see datas of my account

Priority: B
Risk: Low
Story points: 2

- [x] add user information

- [x] Add profile button on navigation bar

**Comment by chimano** [comment]
![screenshot from 2018-03-21 21-52-29](https://user-images.githubusercontent.com/26588048/37746774-32a65324-2d52-11e8-931c-add9fce068a5.png)
