### ISSUE TITLE
sort by feature in homepage

### ISSUE THREAD

**Issue by GuiWukai** [chimano/SOEN341_SA2#155]
As a user, I want to be able to sort my questions by date and points so that I can view the most recent questions or hottest questions

Story points: 1
Priority: B
Risk: Low

**Comment by chimano** [comment]
![screenshot from 2018-03-21 22-33-39](https://user-images.githubusercontent.com/26588048/37747934-f0fb7408-2d57-11e8-8442-414a99c05b22.png)
