### ISSUE TITLE
backend add modify profile information functionality

### ISSUE THREAD

**Issue by GuiWukai** [chimano/SOEN341_SA2#156]
For user story #152 

Add function to:

- [ ] modify about me

**Comment by dobrovv** [comment]
I have added it in #124 
You can do a request to
POST localhost:8000/api/user/me/
with JSON Body:
{"about_me":"My User's profile", "last_name":"MyName", "first_name":"MyFam", "email": null}
(If a parameter is omitted or set to null than it's not modified)

**Comment by GuiWukai** [comment]
Ohhh alright sorry about that. I'm gonna close this task

**Comment by dobrovv** [comment]
Np, I should add it to the wiki!
