### ISSUE TITLE
Can't vote in search page

### ISSUE THREAD

**Issue by GuiWukai** [chimano/SOEN341_SA2#159]
Voting doesn't work in searchpage

- [ ] fix this problem

**Comment by dobrovv** [comment]
Looks like the bug is due to axios attaching the request to the current location

From homepage
Request URL: http://localhost:8000/api/question/vote/
{vote_type: "UP", q_id: 22}

From search page 
Request URL: http://localhost:8000/search/api/question/vote/
{vote_type: "UP", q_id: 18}

**Comment by irinafakotakis** [comment]
We decided the user should not be able to vote on the Question from the Question List generated by the search, so those buttons will be removed. Users will then only be able to vote on the question from the AnswerPage of that question.

**Comment by irinafakotakis** [comment]
Due to change mentioned in previous comment, this issue no longer needed.
