### ISSUE TITLE
Additional search filters

### ISSUE THREAD

**Issue by dobrovv** [chimano/SOEN341_SA2#172]
As a user, I'd like to select additional filters used when searching for questions on the search page.

Story points: 3
Priority: Medium
Risk: Low

Tasks:
- [x] Add search filters bar to the question page (~2 hours)
- [x] Modify getApiSearch() to include filters (~10 minutes)
- [x] Modify SearchView to filter according to the specified filters (~1 hour)

**Comment by chimano** [comment]
![screenshot from 2018-03-21 18-29-13](https://user-images.githubusercontent.com/26588048/37740910-cd4ad638-2d35-11e8-962a-c8c32c4cb9a0.png)
