### ISSUE TITLE
Add tags to question boxes

### ISSUE THREAD

**Issue by GuiWukai** [chimano/SOEN341_SA2#175]
As a user, I want to see tags of questions on the homepage so that I can have more details on the question

Story points: 1

**Comment by chimano** [comment]
![image](https://user-images.githubusercontent.com/26588048/37740458-369d8cd6-2d34-11e8-8f55-e3b18c4559c4.png)

**Comment by chimano** [comment]
![screenshot from 2018-03-21 18-19-28](https://user-images.githubusercontent.com/26588048/37740528-74fbe478-2d34-11e8-8231-e4ebe0197e80.png)
