### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by GuiWukai** [chimano/SOEN341_SA2#24]
As a user, I'd like to see a list of the top questions in the homepage.

Story points: 2
Priority: A
Risk: Low

Tasks:

- [x] Make the ui design of a list of the top questions that contains the following elements: question title, number of votes, number of answers, user that posted the question and his number of points (~30 minutes)(@guiwukai)
- [x] Connect the database with the frontend to display real data of the database (~20 minutes)(@vincentsun870530,@guiwukai)
- [x] Make footer (~20minutes)(@vincentsun870530)

**Comment by chimano** [comment]
![screenshot from 2018-03-06 19-40-29](https://user-images.githubusercontent.com/26588048/37067092-4554fe9a-2176-11e8-807c-7b94f955122d.png)
