### ISSUE TITLE
User point system

### ISSUE THREAD

**Issue by GuiWukai** [chimano/SOEN341_SA2#25]
As a user, I'd like to have a point system to get points when I answer questions.

Story points: 4
Priority: B
Risk: High

**Comment by chimano** [comment]
This might take slightly longer than what is indicated. The programmer will also have to stop users from voting positively twice on the same answer.

**Comment by irinafakotakis** [comment]
For now, the Account tab is always visible, whether a user is logged in or not. Access to the Account page (tab in the navigation bar) should be updated to only show up after a user is logged in.

**Comment by chimano** [comment]
![image](https://user-images.githubusercontent.com/26588048/37067397-91cfd744-2177-11e8-88cf-ee84beab11cc.png)
