### ISSUE TITLE
Add a picture to my profile page

### ISSUE THREAD

**Issue by vincentsun870530** [chimano/SOEN341_SA2#31]
As a user, I'd like to add a picture to my profile page so that I can have a profile picture. 

Story points: 2
Priority: C
Risk: Low

Tasks:

- [ ] Create UI(upload button and image space) in user profile page (~ 15 minutes)
- [ ] Create HTTP requests(GET/POST/DELETE) for user picture in API(~ 30 minutes)

**Comment by chimano** [comment]
Closed because of a change in priorities
