### ISSUE TITLE
Create UI for voting on questions and answers

### ISSUE THREAD

**Issue by chimano** [chimano/SOEN341_SA2#62]
for user story #25 
The user should be able to vote for positively or negatively for a question from the page. This includes the connection to the backend as well.

**Comment by irinafakotakis** [comment]
<img width="876" alt="screen shot 2018-03-07 at 11 08 46 pm" src="https://user-images.githubusercontent.com/22283138/37132611-865fd6c6-225c-11e8-980b-fbca7c972e35.png">
