### ISSUE TITLE
Separate questions by tag

### ISSUE THREAD

**Issue by chimano** [chimano/SOEN341_SA2#92]
As a user, I'd like to see questions based on their category so that I can easily find the questions that interest me.

Story points: 4
Priority: A
Risk: Low

**Comment by anthonyle17** [comment]
<img width="941" alt="screen shot 2018-03-17 at 5 55 03 pm" src="https://user-images.githubusercontent.com/35607307/37560318-59de7a28-2a0c-11e8-88e6-cf57267d8dc7.png">
